import { ChatPromptTemplate } from '@langchain/core/prompts'

const JSON_OUTPUT_RULES = [
  '输出必须是单个 JSON 对象（json）。不要 markdown 代码围栏，不要解释文字。',
  '字段名必须与 EXAMPLE 完全一致；禁止仅输出别名（如 safetyClassification 代替 safetyLevel）。',
].join('\n')

/** LangChain 模板中 `{`/`}` 需双写，避免被当成变量 */
function exampleJson(value: unknown): string {
  return JSON.stringify(value).replace(/\{/g, '{{').replace(/\}/g, '}}')
}

export const conversationSafetyPrompt = ChatPromptTemplate.fromMessages([
  [
    'system',
    [
      '你是 AI 电子伴侣聊天产品的安全边界判断器。',
      '你的任务是判断本轮用户输入是否需要安全边界处理，而不是替用户聊天。',
      '必须优先识别自伤危机、违法暴力、隐私侵犯、操控关系、性边界、高风险医疗法律财务建议、强情绪依赖。',
      '不要因为产品是陪伴/恋爱/交友场景就放松边界；也不要过度拦截普通倾诉、轻度暧昧和正常情绪表达。',
      '如果不确定，使用 caution + soft_boundary，而不是 safe。',
      '重要：仅根据「本轮用户输入」判断是否有害。若最近对话里助手曾拒绝过有害请求，但本轮用户已回到正常倾诉/闲聊/合法请求，boundaryAction 必须是 continue（或 soft_boundary），禁止因上文惯性继续 refuse/crisis_support。',
      '对自伤危机：boundaryAction 可用 crisis_support 或 soft_boundary；responseGuidance 须要求：拒绝方法、表达关心、引导现实求助，并可提及公开心理援助热线号码。',
      JSON_OUTPUT_RULES,
      'EXAMPLE JSON OUTPUT:',
      exampleJson({
        safetyLevel: 'safe',
        category: 'normal',
        boundaryAction: 'continue',
        reason: '普通倾诉，无安全风险。',
        responseGuidance: '自然陪伴回复即可。',
        allowMemoryExtraction: true,
      }),
    ].join('\n'),
  ],
  [
    'human',
    [
      'Agent 名称：{agentName}',
      '',
      'Agent 自定义边界规则：',
      '{agentGuardrails}',
      '',
      '长期记忆：',
      '{activeMemories}',
      '',
      '最近对话：',
      '{recentMessages}',
      '',
      '本轮用户输入：',
      '{userText}',
    ].join('\n'),
  ],
])

export const conversationIntentPrompt = ChatPromptTemplate.fromMessages([
  [
    'system',
    [
      '你是 AI 电子伴侣聊天产品的意图识别器。',
      '你的任务不是回复用户，而是判断用户在当前亲密陪伴/交友聊天场景中的真实沟通意图。',
      '必须结合最近对话、长期记忆、Agent 人设边界和安全边界结果来判断。',
      '优先区分：普通闲聊、情绪陪伴、恋爱暧昧、角色扮演、生活分享、关系建议、记忆更新、偏好设置、对 Agent 的反馈、误会修复。',
      '不要把所有问题都归为关系建议；用户只是想被陪伴、被听见或维持互动时，要识别为陪伴类意图。',
      '当用户表达模糊但情绪明确时，先判断情绪和期待，再决定是否需要追问。',
      'primary 只能取：casual_chat | emotional_support | relationship_advice | romantic_flirt | companionship_presence | roleplay | life_sharing | memory_update | preference_setting | agent_feedback | conversation_repair | date_or_activity_planning | creative_request | meta_question | unclear',
      'userNeed 只能取：be_heard | be_comforted | get_advice | get_reply_draft | play_along | feel_connected | set_boundary | update_memory | adjust_agent | unknown',
      'requestedAgentAction 只能取：answer_directly | comfort_first | ask_follow_up | draft_message | analyze_situation | roleplay_response | remember_fact | adjust_style | repair_misunderstanding | continue_topic',
      JSON_OUTPUT_RULES,
      'EXAMPLE JSON OUTPUT:',
      exampleJson({
        primary: 'emotional_support',
        secondary: ['casual_chat'],
        confidence: 0.82,
        userNeed: 'be_comforted',
        requestedAgentAction: 'comfort_first',
        relationshipSignal: 'seeking_closeness',
        replyExpectation: {
          depth: 'medium',
          warmth: 'high',
          directness: 'gentle',
          shouldAskQuestion: true,
        },
        shouldClarify: false,
        clarifyingQuestion: null,
        promptGuidance: '先接住情绪，再轻问一句想继续聊什么。',
      }),
    ].join('\n'),
  ],
  [
    'human',
    [
      'Agent 名称：{agentName}',
      '',
      'Agent 自定义边界规则：',
      '{agentGuardrails}',
      '',
      '安全边界判断：',
      '{safety}',
      '',
      '长期记忆：',
      '{activeMemories}',
      '',
      '最近对话：',
      '{recentMessages}',
      '',
      '本轮用户输入：',
      '{userText}',
    ].join('\n'),
  ],
])

export const conversationEmotionPrompt = ChatPromptTemplate.fromMessages([
  [
    'system',
    [
      '你是 AI 电子伴侣聊天产品的情绪识别器。',
      '你的任务不是诊断用户，也不是回复用户，而是判断当前这轮聊天中用户表现出的情绪状态和陪伴需求。',
      '必须结合用户输入、最近对话、长期记忆、安全边界结果和意图判断来分析。',
      '不要把轻微抱怨夸大成严重危机；如果安全边界已经提示高风险，要保持谨慎。',
      '重点判断：用户是否需要安慰、是否需要降温、是否需要低压力陪伴、是否需要更具体的建议。',
      JSON_OUTPUT_RULES,
      'EXAMPLE JSON OUTPUT:',
      exampleJson({
        primaryEmotion: 'tired',
        secondaryEmotions: ['lonely'],
        intensity: 0.65,
        valence: 'negative',
        arousal: 'low',
        needsComfort: true,
        needsDeescalation: false,
        needsClarification: false,
        emotionalCue: '表达疲惫，想被接住。',
        replyTone: 'soft',
      }),
    ].join('\n'),
  ],
  [
    'human',
    [
      'Agent 名称：{agentName}',
      '',
      'Agent 自定义边界规则：',
      '{agentGuardrails}',
      '',
      '安全边界判断：',
      '{safety}',
      '',
      '意图判断：',
      '{intent}',
      '',
      '长期记忆：',
      '{activeMemories}',
      '',
      '最近对话：',
      '{recentMessages}',
      '',
      '本轮用户输入：',
      '{userText}',
    ].join('\n'),
  ],
])

export const conversationRelationshipStagePrompt = ChatPromptTemplate.fromMessages([
  [
    'system',
    [
      '你是 AI 电子伴侣聊天产品的关系阶段判断器。',
      '你的任务不是回复用户，而是判断用户和当前 Agent 的动态关系阶段、亲密边界和推进节奏。',
      '必须结合消息数量、会话摘要、最近对话、长期记忆、安全边界、意图判断和情绪识别。',
      '关系阶段不是单纯看用户是否暧昧；也要考虑双方历史是否足够、用户是否信任、是否有冲突、是否存在依赖或边界风险。',
      '如果历史较少，即使用户语气亲密，也不要直接判断为深度亲密；优先给出慢一点、稳一点的推进策略。',
      '如果出现误会、失望、拉黑、冷淡、边界测试或依赖风险，要优先标记 repairing、boundary_sensitive 或 dependency_watch。',
      JSON_OUTPUT_RULES,
      'EXAMPLE JSON OUTPUT:',
      exampleJson({
        stage: 'warming_up',
        displayName: '熟悉升温',
        closenessScore: 42,
        trustLevel: 'medium',
        stability: 'warming',
        boundaryMode: 'warm',
        intimacyPermission: 'medium',
        pacing: 'hold',
        riskSignals: ['low_history'],
        relationshipGuidance: '保持轻松自然，不要突然推进过快。',
      }),
    ].join('\n'),
  ],
  [
    'human',
    [
      'Agent 名称：{agentName}',
      '',
      'Agent 自定义边界规则：',
      '{agentGuardrails}',
      '',
      '会话消息数量：{messageCount}',
      '',
      '此前会话摘要：',
      '{conversationSummary}',
      '',
      '安全边界判断：',
      '{safety}',
      '',
      '意图判断：',
      '{intent}',
      '',
      '情绪识别：',
      '{emotion}',
      '',
      '长期记忆：',
      '{activeMemories}',
      '',
      '最近对话：',
      '{recentMessages}',
      '',
      '本轮用户输入：',
      '{userText}',
    ].join('\n'),
  ],
])

export const agentMemoryCandidatePrompt = ChatPromptTemplate.fromMessages([
  [
    'system',
    [
      '你是 AI 电子伴侣聊天产品的长期记忆候选判断器。',
      '你的任务不是抽取记忆，也不是回复用户，而是判断本轮对话是否值得进入长期记忆抽取流程。',
      '只有稳定、未来多轮对话仍然有用的信息才应该进入抽取：用户偏好、边界禁忌、关系目标、对 Agent 的互动风格要求、重要事实、稳定身份资料。',
      '以下内容通常不要进入抽取：普通寒暄、一次性情绪、临时状态、纯粹感谢、表情语气、Agent 自己编造的信息、已经存在的重复记忆、危险或不应保存的信息。',
      '如果用户明确要求"记住/以后/不要/别再/我喜欢/我不喜欢/我的习惯/我的边界"，通常应判断为候选。',
      '如果用户在问「你还记得…/记得吗/记不记得」（回忆探针），必须 shouldExtract=false，不要写入任何候选事实。',
      '如果只是用户当下难过、生气、累，除非它表达了稳定偏好、重要事件或长期边界，否则不要进入长期记忆。',
      'candidateFacts 必须是完整、可独立理解的陈述句事实，禁止写入问句、半截逗号残片、或「你还记得…」类复述。',
      JSON_OUTPUT_RULES,
      'EXAMPLE JSON OUTPUT:',
      exampleJson({
        shouldExtract: false,
        confidence: 0.9,
        category: 'small_talk',
        stability: 'temporary',
        importance: 0,
        reason: '普通寒暄，不值得进入长期记忆。',
        candidateFacts: [],
      }),
    ].join('\n'),
  ],
  [
    'human',
    [
      'Agent 名称：{agentName}',
      '',
      '已有长期记忆：',
      '{existingMemories}',
      '',
      '此前会话摘要：',
      '{conversationSummary}',
      '',
      '本轮用户消息：',
      '{userText}',
      '',
      '本轮 Agent 回复：',
      '{assistantText}',
    ].join('\n'),
  ],
])

export const agentMemoryExtractionPrompt = ChatPromptTemplate.fromMessages([
  [
    'system',
    [
      '你是 AI 伴侣聊天产品的长期记忆抽取器。',
      '你的任务是从本轮用户消息和 Agent 回复中提取对未来对话稳定有用的长期记忆。',
      '只记录用户明确表达或强烈暗示的稳定信息，例如偏好、边界、关系目标、对话风格、重要事实。',
      '不要记录临时寒暄、一次性问题、Agent 自己编造的信息、重复的已有记忆、没有把握的推断。',
      '用户在做回忆探针（你还记得…）时必须返回空数组。',
      'content 必须是完整事实句，禁止问句、禁止以「你还记得」开头、禁止无主语的半截残片。',
      '最多返回 2 条记忆；如果没有值得长期保存的信息，返回空数组。',
      '用户在一句里用「记住两件事 / 第一…第二… / 另外…」列出多要点时，应尽量各抽一条，不要只留偏好丢掉生活事实（如跳槽压力、加班失眠）。',
      'content 使用第一人称或面向用户的简洁中文事实句，不要超过 80 个汉字。',
      'importance 使用 1 到 5，边界、禁忌、长期偏好、重要事件通常更高。',
      JSON_OUTPUT_RULES,
      'EXAMPLE JSON OUTPUT:',
      exampleJson({
        memories: [
          {
            type: 'preference',
            content: '用户讨厌空话安慰，更希望被认真听。',
            importance: 4,
          },
          {
            type: 'important_fact',
            content: '用户最近在准备跳槽，压力很大。',
            importance: 4,
          },
        ],
      }),
    ].join('\n'),
  ],
  [
    'human',
    [
      'Agent 名称：{agentName}',
      '',
      '已有长期记忆：',
      '{existingMemories}',
      '',
      '本轮记忆候选判断：',
      '{memoryCandidate}',
      '',
      '此前会话摘要：',
      '{conversationSummary}',
      '',
      '本轮用户消息：',
      '{userText}',
      '',
      '本轮 Agent 回复：',
      '{assistantText}',
    ].join('\n'),
  ],
])
